disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Jorden Norton | Blog"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"
#logo = "profile-pic.png"
author = { name = "Jorden Norton", image = "profile-pic.png", headline = "Let’s Automate, Innovate, and Make Things Happen", bio = "", links = [
    { linkedin = "https://www.linkedin.com/in/jorden-norton-086039161/" },
    { github = "https://github.com/nunocoracao/blowfish" },
    { instagram = "https://masto.ai/@blowfish" },
] }
secondaryLogo = "profile-pic.png"
